NumPy (Numerical Python) is a Python library used for fast numerical and scientific computing, mainly providing support for multidimensional arrays (ndarray) and mathematical operations on them.

In [35]:
!pip install numpy


In [36]:
import numpy  as np 
## create a 1D array
array1D = np.array([1,2,3,4,5])
print("1D Array:", array1D)
print("Shape of 1D Array:", array1D.shape)
print("Data Type of 1D Array:", array1D.dtype)
print(type(array1D))


1D Array: [1 2 3 4 5]
Shape of 1D Array: (5,)
Data Type of 1D Array: int64
<class 'numpy.ndarray'>


In [37]:
array2= np.array([1,2,3,4,5,])
array2.reshape(1,5) ## reshape to 1 row and 5 columns



array([[1, 2, 3, 4, 5]])

In [ ]:
array2D = np.array([1,2,3,4,5,6]).reshape(2,3)
print("2D Array:\n", array2D)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [39]:
array2 = np.array([[1,2,3,4,5]])
array2.shape








(1, 5)

In [ ]:
# Create a 2D array
array2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(array2)
array2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [ ]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# identity matrix 
np.eye(4)





array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
##  Attributes of numpy array 
arr = np.array([[1,2,3],[4,5,6]])
print("Array :\n" ,arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Number of Dimensions:", arr.ndim)
print("Size (Total number of elements):", arr.size)
print("Data type :",arr.dtype)
print("Item size (in bytes):", arr.itemsize)
print("Memory Address of first element:", arr.ctypes.data)

Array :
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data Type: int64
Number of Dimensions: 2
Size (Total number of elements): 6
Data type : int64
Item size (in bytes): 8
Memory Address of first element: 2805567984736


In [12]:
 # numpy vectorized operations
a = np.array([1,2,3,4])
b = np.array([10,20,30,40 ])
print("Array a:", a)
print("Array b:", b)       
print("Addition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)
print("Exponentiation:", a ** 2)
print("Square Root of b:", np.sqrt(b))


Array a: [1 2 3 4]
Array b: [10 20 30 40]
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Exponentiation: [ 1  4  9 16]
Square Root of b: [3.16227766 4.47213595 5.47722558 6.32455532]


In [13]:
 ## universal functions
arr = np.array([1,4,9,16,25])
print("Original Array:", arr)
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Natural Logarithm:", np.log(arr))
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))


Original Array: [ 1  4  9 16 25]
Square Root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Natural Logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Mean: 11.0
Standard Deviation: 8.648699324175862


In [14]:
## array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array:\n", arr)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
arr[0]


array([1, 2, 3, 4])

In [16]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [20]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [21]:
## modifiy array elements
arr[0,0]=99
print(arr)


[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr[1:]=50
print(arr)


[[99  2  3  4]
 [50 50 50 50]
 [50 50 50 50]]


In [26]:
arr[:2]=100
print(arr)

[[100 100 100 100]
 [100 100 100 100]
 [ 50 100  50  50]]


In [29]:
arr[:-2]=10
print(arr)

[[ 10  10  10  10]
 [100 100 100 100]
 [ 50 100  50  50]]


In [ ]:
### statictical concepts -- Normalization  
## to have a mean of 0  and s tadard deviation of 1 
data = np.array([10,20,30,40,50])
mean = np.mean(data) 
std_dev= np.std(data)
## noramalize the data 
###Normalization is a technique to rescale data so that it fits within a certain range, 
# often to make datasets comparable or suitable for analysis.
noramlized_data= (data-mean)/std_dev
print("Normalized Data:", noramlized_data)
#!/usr/bin/env python3

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [34]:
## logical operations on arrays
data = np.array([1,2,3,4,5,6,7,8,9,10])
print("Original Data:", data)
data[(data>=5)&(data<=8)]


Original Data: [ 1  2  3  4  5  6  7  8  9 10]


array([5, 6, 7, 8])